### ISSUE TITLE
Add VSCode extension to open-vsx.org

### ISSUE THREAD

**Issue by shaal** [romainmenke/vscode-extensions#1]
Thank you for creating the `CSSTools Design Tokens` awesome extension.
Unfortunately, I cannot use this extension in https://gitpod.io 😢 

TLDR: 
Gitpod is an open-source project, that provides a full development environment in the browser.
Microsoft prohibits the direct use of their marketplace by any non-Microsoft software.

It would be wonderful if you could publish your VSCode extension to the vendor-neutral, open source Open VSX registry. 🎉 

All the details and step-by-step instructions are here -
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

Please let me know if I can help in any way.

**Comment by romainmenke** [comment]
@shaal Thank you for your interest in this extension!

This should now be published : https://open-vsx.org/extension/RomainMenke/csstools-design-tokens

_I am still waiting for confirmation on the namespace claiming process._

Please let me know if there is anything that doesn't work as you would like in the extension.

**Comment by shaal** [comment]
@romainmenke it is now available in Gitpod workspaces.
Thank you very much for your prompt response.

The one question/request I have regarding extension, is if there would be a "devtools" extension, to use on pages that were built with PostCSS design-tokens, and that devtools extension would show what design token it was based on (instead of just the compiled raw value).

**Comment by romainmenke** [comment]
> Thank you very much for your prompt response.

You're welcome.

> is if there would be a "devtools" extension, to use on pages that were built with PostCSS design-tokens, and that devtools extension would show what design token it was based on (instead of just the compiled raw value).

As a browser extension?
That might be possible by looking at the sourcemaps but would be outside the scope of this project :)
