### ISSUE TITLE
Making the gradient extension available for more `languageId`

### ISSUE THREAD

**Issue by meduzen** [romainmenke/vscode-extensions#3]
Hi, and thank you for your work in the CSS area!

The gradient preview only shows when the detected language is `css`:

https://github.com/romainmenke/vscode-extensions/blob/b1debc8dddc593b06f9d9056518e5b557ebd3428/css/css-gradients-preview/src/extension.ts#L166

I’m not experimented in the development of VSCode extensions, but I guess it’s still worth trying to run the AST when `scss` (and `postcss`) are the detected `languageId`.

Maybe it could also work for `html` or some templating languages, as styles can be inlined (`<style>`). 🤔

**Comment by romainmenke** [comment]
see : https://github.com/romainmenke/vscode-extensions/issues/2

**Comment by romainmenke** [comment]
The main issue with adding support for something like `scss` is that I don't know sass, it's ecosystems or the expectations of users.

I will not be able to support/maintain a feature like this.

It's somewhat different from the `postcss` language identifier because at least `scss` has a definition. So it definitely seems possible, but maybe this is best done in a different extensions?

**Comment by meduzen** [comment]
Sorry, I completely forgot to look the existing issue first. 😐

I understand your point of view. Could a setting for this extension be a possibility, in order to let user specify additional `languageID`s? The setting would provide clear indication that only `css` is officially supported.

I have no idea what would be the failure rate of the AST, but there are a number of scenarii where it will succeed. Maybe another extension is wiser. 😄

I let you close the issue or reconvert it into a feature request for something like a setting.

**Comment by romainmenke** [comment]
> Sorry, I completely forgot to look the existing issue first

That's totally fine :)
I prefer a duplicate issue over not hearing any feedback.

-------

I tried something : https://github.com/romainmenke/vscode-extensions/commit/5da331ca84bda36153fe8fed533e84f285471413#diff-78e7afdf77a5b95c5aac9985d365aa1f7d2a1889d41a76cda3302c4b5de2357bR180-R184

No idea if this will work :D

**Comment by meduzen** [comment]
Ha ha, excellent idea to bring `post-scss` in the game.

And… AMAGAD, IT WORKS §§§

https://user-images.githubusercontent.com/9340937/230607998-4f2334ed-9ac2-4c5c-ac0b-8f0e40543606.mp4

I also tried it in a SCSS file with more complexity, and it also worked. 👍

**Comment by romainmenke** [comment]
Very cool!

<img src="https://media.giphy.com/media/jpbnoe3UIa8TU8LM13/giphy.gif" width="50" >
